# Copyright (c) 2025 Roman Reinelt / RNLT Labs
# All rights reserved.

# Local Development Database
# Run with: docker-compose up -d

services:
  postgres:
    image: postgres:16-alpine
    container_name: massava-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: massava
      POSTGRES_PASSWORD: massava_dev_password
      POSTGRES_DB: massava_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U massava"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: massava_postgres_data
