/**
 * Copyright (c) 2025 Roman Reinelt / RNLT Labs
 * All rights reserved.
 *
 * Health Data Access Audit Logger
 *
 * GDPR Art. 32 Compliance - Log all access to health data
 * Records who accessed what health data and when
 *
 * IMPORTANT: Uses dependency injection to avoid circular dependency with Prisma client
 */

import { PrismaClient } from '@/app/generated/prisma';
import { logger } from '../logger';

/**
 * Health data access log entry
 */
export interface HealthDataAccessLog {
  action: 'ENCRYPT' | 'DECRYPT' | 'ACCESS' | 'EXPORT' | 'DELETE';
  userId: string;
  bookingId: string;
  timestamp: Date;
  ipAddress?: string;
  userAgent?: string;
  details?: string;
}

/**
 * Log health data access to audit trail
 *
 * Uses dependency injection for Prisma client to avoid circular dependencies.
 * Creates a fresh Prisma client instance if none is provided.
 *
 * @param log - Health data access log entry
 * @param prismaClient - Optional Prisma client instance (for testing and avoiding circular deps)
 */
export async function logHealthDataAccess(
  log: HealthDataAccessLog,
  prismaClient?: PrismaClient
): Promise<void> {
  try {
    // Log to application logger (for external monitoring like GlitchTip)
    logger.info('Health data access', {
      action: log.action,
      userId: log.userId,
      bookingId: log.bookingId,
      timestamp: log.timestamp.toISOString(),
      ipAddress: log.ipAddress ? anonymizeIp(log.ipAddress) : undefined,
      userAgent: log.userAgent,
      details: log.details,
      gdprCompliance: 'Art. 32 GDPR - Security of Processing',
    });

    // Store in database audit log
    // Uses a fresh Prisma client to avoid circular dependency with the extended client
    try {
      const client = prismaClient || new PrismaClient();

      await client.auditLog.create({
        data: {
          action: `HEALTH_DATA_${log.action}`,
          userId: log.userId,
          resource: 'BOOKING',
          resourceId: log.bookingId,
          ipAddress: log.ipAddress ? anonymizeIp(log.ipAddress) : null,
          userAgent: log.userAgent || null,
          metadata: log.details || undefined,
          // timestamp is auto-generated by Prisma via @default(now())
        },
      });

      // Clean up client if we created it
      if (!prismaClient) {
        await client.$disconnect();
      }
    } catch (dbError) {
      // If AuditLog table doesn't exist yet, only log to application logger
      // This allows the encryption system to work before full audit infrastructure is ready
      logger.warn('Failed to store health data access in database audit log', {
        error: dbError instanceof Error ? dbError.message : 'Unknown error',
        fallback: 'Logged to application logger only',
      });
    }
  } catch (error) {
    // Never throw errors from audit logging - it should not break the application
    logger.error('Health data audit logging failed', {
      error: error instanceof Error ? error.message : 'Unknown error',
      log,
    });
  }
}

/**
 * Batch log multiple health data access events
 * More efficient than calling logHealthDataAccess multiple times
 *
 * @param logs - Array of health data access log entries
 * @param prismaClient - Optional Prisma client instance
 */
export async function logHealthDataAccessBatch(
  logs: HealthDataAccessLog[],
  prismaClient?: PrismaClient
): Promise<void> {
  if (logs.length === 0) return;

  try {
    // Log summary to application logger
    logger.info('Batch health data access', {
      count: logs.length,
      actions: logs.map(log => log.action),
      gdprCompliance: 'Art. 32 GDPR - Security of Processing',
    });

    // Batch insert to database
    try {
      const client = prismaClient || new PrismaClient();

      await client.auditLog.createMany({
        data: logs.map(log => ({
          action: `HEALTH_DATA_${log.action}`,
          userId: log.userId,
          resource: 'BOOKING',
          resourceId: log.bookingId,
          ipAddress: log.ipAddress ? anonymizeIp(log.ipAddress) : null,
          userAgent: log.userAgent || null,
          metadata: log.details || undefined,
        })),
      });

      // Clean up client if we created it
      if (!prismaClient) {
        await client.$disconnect();
      }
    } catch (dbError) {
      logger.warn('Failed to batch store health data access logs', {
        error: dbError instanceof Error ? dbError.message : 'Unknown error',
        count: logs.length,
        fallback: 'Logged to application logger only',
      });
    }
  } catch (error) {
    logger.error('Batch health data audit logging failed', {
      error: error instanceof Error ? error.message : 'Unknown error',
      count: logs.length,
    });
  }
}

/**
 * Anonymize IP address for GDPR compliance
 * Removes last octet for IPv4, last 80 bits for IPv6
 * 
 * @param ip - IP address to anonymize
 * @returns Anonymized IP address
 */
function anonymizeIp(ip: string): string {
  // IPv4
  if (ip.includes('.')) {
    const parts = ip.split('.');
    parts[parts.length - 1] = '0';
    return parts.join('.');
  }

  // IPv6
  if (ip.includes(':')) {
    const parts = ip.split(':');
    // Keep first 48 bits (3 groups), zero out the rest
    return parts.slice(0, 3).join(':') + '::';
  }

  // Unknown format, return as-is
  return ip;
}

/**
 * Query health data access audit logs
 *
 * @param filters - Optional filters for querying logs
 * @param prismaClient - Optional Prisma client instance
 * @returns Array of audit log entries
 */
export async function queryHealthDataAccessLogs(
  filters?: {
    userId?: string;
    bookingId?: string;
    action?: HealthDataAccessLog['action'];
    startDate?: Date;
    endDate?: Date;
  },
  prismaClient?: PrismaClient
): Promise<any[]> {
  try {
    const client = prismaClient || new PrismaClient();

    const where: any = {
      action: {
        startsWith: 'HEALTH_DATA_',
      },
    };

    if (filters?.userId) {
      where.userId = filters.userId;
    }

    if (filters?.bookingId) {
      where.resourceId = filters.bookingId;
    }

    if (filters?.action) {
      where.action = `HEALTH_DATA_${filters.action}`;
    }

    if (filters?.startDate || filters?.endDate) {
      where.timestamp = {};
      if (filters.startDate) {
        where.timestamp.gte = filters.startDate;
      }
      if (filters.endDate) {
        where.timestamp.lte = filters.endDate;
      }
    }

    const logs = await client.auditLog.findMany({
      where,
      orderBy: {
        createdAt: 'desc',
      },
      take: 100, // Limit to prevent performance issues
    });

    // Clean up client if we created it
    if (!prismaClient) {
      await client.$disconnect();
    }

    return logs;
  } catch (error) {
    logger.error('Failed to query health data access logs', {
      error: error instanceof Error ? error.message : 'Unknown error',
      filters,
    });
    return [];
  }
}

/**
 * Export health data access logs for compliance reporting
 *
 * @param userId - User ID to export logs for
 * @param prismaClient - Optional Prisma client instance
 * @returns CSV format logs
 */
export async function exportHealthDataAccessLogs(
  userId: string,
  prismaClient?: PrismaClient
): Promise<string> {
  const logs = await queryHealthDataAccessLogs({ userId }, prismaClient);

  const csv = [
    'Timestamp,Action,Booking ID,IP Address,User Agent',
    ...logs.map((log: any) =>
      [
        log.timestamp.toISOString(),
        log.action,
        log.resourceId,
        log.ipAddress || '',
        log.userAgent || '',
      ].join(',')
    ),
  ].join('\n');

  return csv;
}
